[build]
  command = "npm run build"
  functions = "./dist/server"
  publish = "./dist/client"

[dev]
  functions = "./src/lambda"

#[template.environment]
#  GITHUB_GIST_TOKEN = "set token that has gist access"